spring:
  liquibase:
      change-log: classpath:/db/changelog/db.changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/rentalcars
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true